### ISSUE TITLE
Support for initial test of query

### ISSUE THREAD

**Issue by trading-peter** [Victor-Bernabe/lit-media-query#1]
I need to get an initial run of the media query when my app boots up. Do you think this would be a good addition to you element? I would like to contribute a pr for this.

The idea would be to add a property like `initial-update` to check the query when the element is connected to the page. What do you think about this?

**Comment by kaseyhinton** [comment]
I also am in need of this same feature which is preventing me from using this component.

**Comment by smashah** [comment]
@kaseyhinton @trading-peter 

Try this

https://gist.github.com/smashah/fa04a3c408568fef30224e155e445ccf

thanks

**Comment by Victor-Bernabe** [comment]
Should be fixed now with bdefb52a110c65e2595b3c32548b359a144f99f8.
