### ISSUE TITLE
Does not cleanup listeners on disconnectedCallback

### ISSUE THREAD

**Issue by stalniy** [Victor-Bernabe/lit-media-query#2]
The element listens events on global objects but doesn't remove listeners when it's destroyed (it should be in `disconnectedCallback`)

**Comment by smashah** [comment]
@stalniy https://gist.github.com/smashah/fa04a3c408568fef30224e155e445ccf

**Comment by stalniy** [comment]
I used a wrapper function around `window.matchMedia`, directly in my components

**Comment by Victor-Bernabe** [comment]
Should be fixed now with aa1faf20812ae0d0ef615a80e0c5ed5b6091d481.
